name = "visitor-stats"
main = "works.js"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "GOLD_PRICE_CACHE"
id = "301ba411dab34e1993c94ec202448118"

[[d1_databases]]
binding = "DB"
database_name = "visitor-stats-db"
database_id = "3b506248-f6ff-4878-ac86-3744bd5de05e"

[[analytics_engine_datasets]]
binding = "analytic_engine"
dataset = "analytic_event"

[triggers]
crons = ["*/1 * * * *", "*/2 * * * *", "*/5 * * * *", "0 0 * * *"]
