name = "meownote-api"
main = "index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "../dist"

[[d1_databases]]
binding = "DB"
database_name = "visitor-stats-db"
database_id = "3b506248-f6ff-4878-ac86-3744bd5de05e"

[[kv_namespaces]]
binding = "GOLD_PRICE_CACHE"
id = "301ba411dab34e1993c94ec202448118"

[[r2_buckets]]
binding = "R2"
bucket_name = "meownote-files"

[vars]
ENVIRONMENT = "production"

[env.development]
name = "meownote-api-dev"

[env.development.vars]
ENVIRONMENT = "development"

[triggers]
crons = [ "*/5 * * * *" ]
